### ISSUE TITLE
this code doesn't work!

### ISSUE THREAD

**Issue by MasheraAnna** [akurniawan/pytorch-sentiment-analysis#1]
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    label_size=train_dataset.category_size)
  File "/Users/anyuta/Documents/ingenix/education/2ndMTS-lection/model.py", line 57, in __init__
    cnn_config = config["cnn"]
KeyError: 'cnn'

**Comment by akurniawan** [comment]
Hi @MasheraAnna, sorry for the trouble. Do you mind telling me how did you run the model? I have just updated the configuration and give the example to run the model

**Comment by akurniawan** [comment]
hopefully this problem is the same as #2, will close this issue for now. please reopen it if you still experiencing the problem. I also in the middle of refactoring the code using [ignite](https://github.com/pytorch/ignite) and torch text hoping to make the code more readable. stay tuned!
