### ISSUE TITLE
Keyerror

### ISSUE THREAD

**Issue by arun-taiger** [akurniawan/pytorch-sentiment-analysis#2]
File "main.py", line 74, in <module>
    for data_bucket, category_bucket, seq_len_bucket in train_data:
  File "/Users/*/anaconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/Users/*/anaconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
  File "main.py", line 74, in <module>
    for data_bucket, category_bucket, seq_len_bucket in train_data:
  File "/Users/*/anaconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/Users/*/anaconda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n'Traceback (most recent call last):\n

**Comment by akurniawan** [comment]
hi @arun-taiger, thanks for the report!
do you mind to elaborate more what data did you use and how did you run it?

**Comment by arun-taiger** [comment]
[2] http://thinknook.com/twitter-sentiment-analysis-training-corpus-dataset-2012-09-22/

**Comment by akurniawan** [comment]
Hi arun, sorry just get back to you now. I haven’t had a chance to debug the code recently. I will let you know once I have fixed the code

**Comment by akurniawan** [comment]
Hi @arun-taiger, I have just checked the code. Since you are using the data directly from the website and not the one that I have been cleaned up (file from s3), you may need to update the dataset a bit. Because the code assumes there should be only 2 columns at the training data (the text and the sentiment). I will give some prevention for this problem to not happening again and will update the documentation. Please let me know if you have another problem, thanks!

**Comment by arun-taiger** [comment]
But  you can change your code, if there are errors in the corpus just skip those lines  instead  of this

        else:
            print("Need to fix this data:", extracted_csv[0])
            sentence = "a"
            label = "0"
        entity_ids = []

**Comment by akurniawan** [comment]
Yep, I hve made a change ti the code. Now instead of skipping the line, the code will return an exception. In my opinion skipping the line would cause trouble. If all the data has columns > 2, then all lines will be skipped

**Comment by arun-taiger** [comment]
Cool! Makes complete sense.  Please close the issue.
